name: Build dev

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: Build and upload artifact
    #runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: subosito/flutter-action@v2

      - name: Build
        run: dotnet build -o .\outputs\test1.zip

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Build ${{ github.run_number }}
          path: .\outputs\test1.zip 
      - uses: actions/checkout@v1
      # ...
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: ./docfx.json

      # Publish generated site using GitHub Pages
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: _site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxh
  
